# Generated by Django 3.0.5 on 2020-06-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('arxiv_published', models.DateTimeField(blank=True, null=True)),
                ('arxiv_updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('doi_link', models.URLField(blank=True, null=True)),
                ('pdf_link', models.URLField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Author')),
            ],
        ),
    ]
