# Generated by Django 3.0.5 on 2020-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200605_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
