# Generated by Django 3.0.5 on 2020-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200606_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
