# Generated by Django 3.0.5 on 2020-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200606_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(related_name='Authors', to='articles.Article'),
        ),
    ]
