# Generated by Django 3.0.5 on 2020-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_author_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
    ]
