# Generated by Django 3.0.5 on 2020-06-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_author_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='arxiv_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='arxiv_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
