# Generated by Django 3.0.5 on 2020-06-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200607_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
